### ISSUE TITLE
Android min target sdk version 29

### ISSUE THREAD

**Issue by secretmoo35** [DmcSDK/cordova-plugin-mediaPicker#115]
New apps must target at least Android 10 (API level 29) (Ref. https://developer.android.com/distribute/play-policies)

config.xml
`<preference name="android-targetSdkVersion" value="29" />`

![83759364-cff53b00-a649-11ea-977b-ef7911811f6c](https://user-images.githubusercontent.com/14917784/92689616-81062280-f369-11ea-984d-4cc90c51f9bf.jpg)

Test on Huawei Nova 5(Android 10)

This solving the problem from now on Not available anymore (Ref. https://github.com/DmcSDK/cordova-plugin-mediaPicker/issues/110 )

How to fix?

**Comment by pzjyyzs** [comment]
I have the same question. Have you solved this problem ?

**Comment by KazakovVS** [comment]
Having the same issue. Any chances to get it resolved?

**Comment by TDola** [comment]
Got this too, permission issue maybe?

**Comment by TDola** [comment]
Not certain what this fork changed, but it seems to be working?
https://github.com/yjseo29/cordova-plugin-mediaPicker
You know how cordova and plugins are...

**Comment by imgoddqp** [comment]
I have the same question. Have you solved this problem ?

**Comment by imgoddqp** [comment]
I resolve this by add
android:requestLegacyExternalStorage="true"
in the manifest file
![image](https://user-images.githubusercontent.com/24971545/94791563-68d67000-040a-11eb-9c23-83e6b6ecdc86.png)

**Comment by secretmoo35** [comment]
> I resolve this by add
> android:requestLegacyExternalStorage="true"
> in the manifest file
> ![image](https://user-images.githubusercontent.com/24971545/94791563-68d67000-040a-11eb-9c23-83e6b6ecdc86.png)
> 
> 在manifest application中加上
> android:requestLegacyExternalStorage="true"
> Android Q 默认开启沙箱模式 导致出现文件读写失败

It worked on Ionic 3 & Ionic 5. Thanks for recommended.

👍 👍

**Comment by TDola** [comment]
That's only a temporary solution

> Caution: After you update your app to target Android 11 (API level 30), the system ignores the requestLegacyExternalStorage attribute when your app is running on Android 11 devices, so your app must be ready to support scoped storage and to migrate app data for users on those devices.

https://developer.android.com/training/data-storage/use-cases

**Comment by Mr-Anonymous** [comment]
Why is this issue closed? I think the plugin should address this issue since the fix above is only a temporary work-around.

**Comment by rlindgren** [comment]
@TDola How is this working out for you with Android 11?  Have you moved to a different picker again?

**Comment by TDola** [comment]
@rlindgren Not yet, so far we are targeting API 30 and it's still working. I have kind of scheduled it in to be replaced for every upcoming release just in case the thing finally breaks.
