### ISSUE TITLE
Build error: no versions available

### ISSUE THREAD

**Issue by niklaslarssonhultgren** [DmcSDK/cordova-plugin-mediaPicker#124]
Webpack build completed to www folder successfully!
Cordova hook completed. Resuming to run your cordova command...
cordova-plugin-androidx-adapter: Processed 57 source files in 916ms
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=(Hidden path)\AppData\Local\Android\Sdk (recommended setting)
ANDROID_HOME=(Hidden path)\AppData\Local\Android\Sdk (DEPRECATED)
Using Android SDK: (Hidden path)\AppData\Local\Android\Sdk
Reading build config file: (Hidden path)\build.json
Reading the keystore from: (Hidden path)\compare.keystore
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:checkDebugAarMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.dmcBig:mediapicker:+ as no versions of com.dmcBig:mediapicker are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/dmcBig/mediapicker/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/dmcBig/mediapicker/maven-metadata.xml
       - https://maven.google.com/com/dmcBig/mediapicker/maven-metadata.xml
     Required by:
         project :app

Am I missing something? This is when running cordova build android@latest which is currently 10.1.1.

**Comment by orenkatz-lp** [comment]
I was able to resolve it by adding this repo:
    maven {
        url "https://repo.nk2.eu/artifactory/gradle-release"
    }

**Comment by niklaslarssonhultgren** [comment]
> I was able to resolve it by adding this repo: maven { url "https://repo.nk2.eu/artifactory/gradle-release" }

Pardon my newbishness, but in what file did you put it?

**Comment by niklaslarssonhultgren** [comment]
Doing both what @orenkatz-lp suggested and using the following fork seemed to have resolved it for me:
https://github.com/bazuka5801/cordova-plugin-mediaPicker

Thanks @orenkatz-lp
