### ISSUE TITLE
android build sdk 10.x.x

### ISSUE THREAD

**Issue by SqJiggly** [DmcSDK/cordova-plugin-mediaPicker#125]
![image](https://user-images.githubusercontent.com/44308287/147727584-2a6dc197-d577-4e39-850d-2265366bbe2c.png)

**Comment by itbeyond** [comment]
This is not hard to fix - you need to add a file in the projects platforms - android folder called build-extras.gradle the contents of this file as:
```
repositories {
  google()
  mavenCentral()
  jcenter()
}

dependencies {
    implementation 'com.dmcBig:mediapicker'
}
```
This will allow the build process to find the dependency and compile.

**Comment by DmcSDK** [comment]
uninstall old plugin，use new version ，Remember to add jitpack.io in the repositories.gradle file, see readme for details
