### ISSUE TITLE
capacitor 打开多图选择图片未显示

### ISSUE THREAD

**Issue by Ryanccl** [DmcSDK/cordova-plugin-mediaPicker#127]
https://user-images.githubusercontent.com/51909525/162398716-99d93c12-dc5f-4ec6-bfd0-71ecf354ddd2.png

**Comment by Ryanccl** [comment]
解决java.io.FileNotFoundException: /storage/emulated/0/问题
原因是Android 10之后，需要在AndroidManifest.xml文件的application 标签下 加一条属性android:requestLegacyExternalStorage=“true”。如下图所示：

**Comment by DmcSDK** [comment]
@Ryanccl 只要加这一行就可以解决是吧？

**Comment by DmcSDK** [comment]
感谢提醒很多年没有看插件了，最近维护了一把~
