### ISSUE TITLE
MediaPicker.extractThumbnail returns base64 string with line breaks

### ISSUE THREAD

**Issue by ryaa** [DmcSDK/cordova-plugin-mediaPicker#14]
I integrated the plugin into the cordova app and under Android 6.x **MediaPicker.extractThumbnail** method returns an image as base64 string with line breaks and it can't be displayed using the style background-image: 'url(<thumbnail_data>)'
Once i remove the line breaks all works fine.

**Comment by DmcSDK** [comment]
@ryaa OK, I know where the problem lies. I will fix it tomorrow.

**Comment by DmcSDK** [comment]
@ryaa  sir！ I can't reproduce it, but I modified the code and asked you to test the results.

**Comment by ryaa** [comment]
Thanks for a quick turnaround. It seems to be fixed for Android but still the problem on iOS.

**Comment by DmcSDK** [comment]
ok, I modified the IOS code，Please test results by new version，and tell me the result。

**Comment by ryaa** [comment]
Installed 2.3.0 and tested on iOS. All works fine. Thank you for the quick fix.
