### ISSUE TITLE
Plugin dialog lists images that have already been deleted (Android 6.0 on Nexus 5)

### ISSUE THREAD

**Issue by ryaa** [DmcSDK/cordova-plugin-mediaPicker#15]
My application creates a temp directory in Downloads directory and stores some temporary jpeg images there. When those are not needed it deletes the entire temp directory with all the files there.

However when the plugin shows the grid with images it shows empty (black) placeholder in the grid for these already deleted images and allows to select them. The problem is that since the file is selected and the plugin returns the path to non existing file and my app fails with an error.

Here is how the grid with empty placeholders looks like
![screenshot_20180705-145502](https://user-images.githubusercontent.com/3608222/42322259-716d9a3a-8064-11e8-9503-92035d9b648f.png)

**Comment by DmcSDK** [comment]
Ok, I will display a background image that cannot be loaded. The image I got is from the media database of android system. The image you deleted, the media database is not updated in time, so that it can be queried, but the file has been deleted. .

**Comment by ryaa** [comment]
I noticed that if I open one of the file manager (ES File Manager for example) apps and list some directory with the files, then use another application to delete a file the list of the files is not updated and the deleted file is still shown in a file manager application. However when i restart the file manager application it shows the right and updated list of files.
However the plugin is not updating the files even after restart. Is there anyway to force the refresh?

**Comment by DmcSDK** [comment]
Will this problem occur with other mobile phones? I tested that huawei， samsung  can't reproduce this problem.

**Comment by ryaa** [comment]
Yes. The problem is reproducible on Nexus 5 with Android 6.0 and LG Q6 with Android 7.0. 
Please note that i create and delete the temp folder with files programatically. To create i use https://ionicframework.com/docs/native/file/#writeFile and to delete i use https://ionicframework.com/docs/native/file/#removeRecursively

I will try to research it a little bit more on my end and will report if I find anything useful.
Thank you for your support!

**Comment by TDola** [comment]
I'm wondering if it's the plugins fault.

I have been deleting image using the file plugin, and I notice the image stays in the folder on the device, it just becomes "broken".  Trying to access the file again throws code 5, encoding error. Accessing in Windows is also broken.

![image](https://user-images.githubusercontent.com/30079906/42392522-c6b372e4-8118-11e8-8f15-74a447517f7b.png)

![image](https://user-images.githubusercontent.com/30079906/42392541-d3efddf8-8118-11e8-9f8d-49ab4ae6c158.png)

Can't even copy the file.

![image](https://user-images.githubusercontent.com/30079906/42392560-e4262826-8118-11e8-86a7-2813fed5477b.png)

So it seems like Android is having a file system error.  Might have to just handle it with a file exists check, on code 5, tell the user the file is corrupted or deleted.

**Comment by shajeeck** [comment]
I suspect this is due to not scanning the media after deleting the file using cordova-file plugin! 

some plugin like cordova media capture and cordova camera rescan the android media when opened or add new media to gallery, implementing the same with this plugin might resolve. 

refer https://github.com/begrossi/MediaScannerPlugin

**Comment by DmcSDK** [comment]
@shajeeck  
Have you tested this method? Is it valid, if it is valid, I will add it to my plugin.

**Comment by shajeeck** [comment]
I have not tested! It's just my assumption.

1. When images are downloaded, it is added to downloaded folder and Android Media Scanner is called  and the file is added to media content https://developer.android.com/reference/android/media/MediaScannerConnection

2. When image is deleted by the user using cordova file plugin, the original file is deleted, but Media Scanner is not called hence some metadata stays in media content

3. When MediaPicker is taken it reads the metadata and shows the blank icon!

I experienced the same issue when i was using cordova camera plugin and when i capture new image with 'saveToPhotoAlbum' option 'true' it saves to media, then when i delete the file using file plugin and takes Mediapicker again it shows same blank image as shows in this issue. Turning 'saveToPhotoAlbum' option 'false' solved it.

So i guess saving to media is calling Media Scanner and while removing file it is not broadcasted again so the metadata is not removed

**Comment by ryaa** [comment]
Researched this problem more today and it seems that the problem is because of cordova file plugin. When I invoke removeRecursively method it returns success but the directory/files are not removed and the files size is 0.
I added a bug in the cordova file plugin repo - see https://github.com/apache/cordova-plugin-file/issues/241
Let's see what the file plugin developers feedback will be...

**Comment by ryaa** [comment]
I confirm that the problem is not related to this plugin so closing the issue.
