### ISSUE TITLE
I get an error when I try to select several videos

### ISSUE THREAD

**Issue by ricardotera** [DmcSDK/cordova-plugin-mediaPicker#21]
it enters getmedias but this does not return the answer with the url of the videos, in the Xcode it throws a message, but I never have a successful answer, nor an error

Xcode Message:
Status bar could not find cached time string image. Rendering in-process.

**Comment by DmcSDK** [comment]
You may need to wait, because when you select the video I will convert the video to MP4, which takes time.

`//ios Video transcoding compression to MP4 Event(use AVAssetExportPresetMediumQuality)
document.addEventListener("MediaPicker.CompressVideoEvent", function(data) {
    alert(data.status + "||" + data.index);
}, false);`
