### ISSUE TITLE
Convert image format heic to jpg.

### ISSUE THREAD

**Issue by soulmecca** [DmcSDK/cordova-plugin-mediaPicker#24]
Hi, thanks a lot for this great plugin!

What I try to do is getting images from photo library and then read EXIF data. 
The problem is when I use High-Efficiency mode in the camera formats setting on my iPhone, the original image format I got with this plugin is heic not jpeg or jpg. 
I can use MediaPicker.compressImage function to get a jpg format but it seems that EXIF data is stripped away after doing this. 

Is it possible to get the original image with jpg or jpeg format? when I use high-efficiency mode on my iPhone setting?

Or is it possible to get jpg image with EXIF data after using compressImage function?

I really need this feature... 

Thanks for your support in advance.

**Comment by DmcSDK** [comment]
how did get exif data？user exif.js?

**Comment by soulmecca** [comment]
I am using this library https://github.com/exif-js/exif-js.
I found that if I switch to 'Most Compatible' mode in Camera formats in my iPhone setting, I get a jpg file with EXIF data but not with 'High Efficiency' mode which returns heic format. 
I also tried with compressImage function but there is no GPS information. 
There is some EXIF information left like rotation but not GPS one. 

If it's not easy to convert heic to jpg. Would it be possible to return exif data as an element of an object?
like {image: imageData, exif: exifData}.

I wish I can use Object C or swift but cannot help here.

What do you think?

**Comment by DmcSDK** [comment]
I added a new function that might meet your requirements. MediaPicker.getExifForKey

MediaPicker.getExifForKey(resultMedias[i].path,"{GPS}", function(data) { alert(data); }, function(e) { console.log(e) });

**Comment by soulmecca** [comment]
Hi!
I am testing the function and it works perfectly so far!! 
Thank you so much for this awesome plugin.

**Comment by guoyongxin** [comment]
Do you think it is good to let the getMedia function return a non HEIC/HEIF format of resource in a default option?
My point is the plugin mainly work with web and most of time we just need to have a JPG or PNG file in our sandbox. So return a non HEIC format file could be helpful and let the user write less code to get their file.
