### ISSUE TITLE
Feature to get height and width of compressed image

### ISSUE THREAD

**Issue by shajeeck** [DmcSDK/cordova-plugin-mediaPicker#26]
Any possible way to get the height and width of compressed image?

**Comment by DmcSDK** [comment]
Temporarily not supported get  the height and width of compressed image, what is your demand?

**Comment by shajeeck** [comment]
Ok, as it returns the size of the image it would be useful to get the height and width in pixels when images are selected, it will help to correctly display lazy loaded images, virtual scroll and adjust layout even before uploading to server and calculating dimensions.

**Comment by DmcSDK** [comment]
I added a new function that might meet your requirements

`MediaPicker.getExifForKey(resultMedias[i].path,"PixelHeight", function(data) { 
      alert(data); 
}, function(e) { console.log(e) });`

**Comment by shajeeck** [comment]
Great! Thanx for the update
