### ISSUE TITLE
IOS app terminates with error when tried to change folder of media

### ISSUE THREAD

**Issue by shajeeck** [DmcSDK/cordova-plugin-mediaPicker#27]
In IOS after launching mediaPicker and selecting the drop down on top to change the folder terminates the app with below error! 
Is this happening because there are no other folders to show?
I tried on another phone with multiple folders present, it works.

Any help will be appreciated, thanx

WARNING: ['MediaPicker'] took '27.001953' ms. Plugin should use a background thread.
2018-08-06 00:25:55.606015+0300 NTP Live[769:6245] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:]: row (3) beyond bounds (1) for section (0).'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108afe1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x00000001074b9031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108b73975 +[NSException raise:format:] + 197
	3   UIKit                               0x0000000109f2d3c0 -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:] + 1179
	4   UIKit                               0x0000000109f2e391 -[UITableView _scrollToRowAtIndexPath:atScrollPosition:animated:usingPresentationValues:] + 146
	5   UIKit                               0x0000000109f2e21a -[UITableView scrollToRowAtIndexPath:atScrollPosition:animated:] + 123
	6   NTP Live                            0x0000000104c907ff -[AlbumListView setListDataSource:dataNameSource:nowSelectAlbum:] + 479
	7   NTP Live                            0x0000000104c86da9 -[DmcPickerViewController titleTap:] + 1977
	8   UIKit                               0x000000010a3eb54f -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 57
	9   UIKit                               0x000000010a3f4324 _UIGestureRecognizerSendTargetActions + 109
	10  UIKit                               0x000000010a3f1b6c _UIGestureRecognizerSendActions + 307
	11  UIKit                               0x000000010a3f0dc0 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 859
	12  UIKit                               0x000000010a3d5e24 _UIGestureEnvironmentUpdate + 1329
	13  UIKit                               0x000000010a3d58a7 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 484
	14  UIKit                               0x000000010a3d49a9 -[UIGestureEnvironment _updateGesturesForEvent:window:] + 281
	15  UIKit                               0x0000000109e6a7ab -[UIWindow sendEvent:] + 4064
	16  UIKit                               0x0000000109e0e310 -[UIApplication sendEvent:] + 352
	17  UIKit                               0x000000010a74f6af __dispatchPreprocessedEventFromEventQueue + 2796
	18  UIKit                               0x000000010a7522c4 __handleEventQueueInternal + 5949
	19  CoreFoundation                      0x0000000108aa0bb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	20  CoreFoundation                      0x0000000108a854af __CFRunLoopDoSources0 + 271
	21  CoreFoundation                      0x0000000108a84a6f __CFRunLoopRun + 1263
	22  CoreFoundation                      0x0000000108a8430b CFRunLoopRunSpecific + 635
	23  GraphicsServices                    0x00000001081aba73 GSEventRunModal + 62
	24  UIKit                               0x0000000109df3057 UIApplicationMain + 159
	25  NTP Live                            0x0000000104c4f3c1 main + 65
	26  libdyld.dylib                       0x000000011096f955 start + 1
	27  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by DmcSDK** [comment]
Thank you very much, I think this should be a bug.

**Comment by shajeeck** [comment]
Welcome. Is there any thing else to be provided to resolve this issue? 
Can we expect a new release soon? Thanx!

**Comment by DmcSDK** [comment]
@shajeeck  i  fix the bug in 2.3.1

**Comment by shajeeck** [comment]
Great! i will test and reply

**Comment by shajeeck** [comment]
With new update npm 2.3.1 it gives an error due to MediaPicker is not exported!

in platform cordova plugin www folder inside MediaPicker.js the cordova.define function is wrapped two times, hence module MediaPicker is not exported

with android cordova 7.1.1 inside platforms>android>platform_www>cordova-plugin-mediapicker-dmbig>www>MediaPicker.js   Function is wrapped twice! same is the case with IOS

```
cordova.define("cordova-plugin-mediapicker-dmcbig.MediaPicker", function(require, exports, module) {
cordova.define("cordova-plugin-mediapicker-dmcbig.MediaPicker", function(require, exports, module) {
var exec = require('cordova/exec');


var MediaPicker = {
    getMedias:function(arg0, success, error) {
        exec(success, error, "MediaPicker", "getMedias", [arg0]);
    },
    photoLibrary:function(arg0, success, error) {
        exec(success, error, "MediaPicker", "photoLibrary", [arg0]);
    },
    takePhoto:function(arg0, success, error) {
        exec(success, error, "MediaPicker", "takePhoto", [arg0]);
    },
    extractThumbnail:function(arg0, success, error) {
        exec(success, error, "MediaPicker", "extractThumbnail", [arg0]);
    },
    compressEvent:function(s,i) {
        cordova.fireDocumentEvent('MediaPicker.CompressVideoEvent', {'status':s,'index':i});
    },
    compressImage:function(arg0, success, error) {
        exec(success, error, "MediaPicker", "compressImage", [arg0]);
    },
    fileToBlob:function(arg0, success, error) {
        exec(success, error, "MediaPicker", "fileToBlob", [arg0]);
    },
    getExif:function(arg0, success, error) {
        exec(success, error, "MediaPicker", "getExif", [arg0]);
    }
};

module.exports = MediaPicker;



});

});
```

**Comment by DmcSDK** [comment]
sorry ！I uploaded the wrong JS

**Comment by DmcSDK** [comment]
fix

**Comment by shajeeck** [comment]
Hello, i tried the new version 2.3.3 but still i am getting the same error in ios

1. when i have only one image folder and trying to press folder change in top bar
```
2018-08-07 12:35:00.949922+0300 NTP Live[1320:552891] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:]: row (3) beyond bounds (2) for section (0).'
*** First throw call stack:
(0x18102ad8c 0x1801e45ec 0x18102ac6c 0x18b0a5330 0x18b0a5958 0x18afbb0f8 0x10105479c 0x10104b0f0 0x18ae196e8 0x18b3863b4 0x18af7be38 0x18ae18740 0x18b377bd4 0x18ae124d8 0x18ae12010 0x18ae11874 0x18ae101d0 0x18b5f1d1c 0x18b5f42c8 0x18b5ed368 0x180fd3404 0x180fd2c2c 0x180fd079c 0x180ef0da8 0x182ed6020 0x18af10758 0x100e759d8 0x180981fc0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```


2. When there are no videos in my iphone and i try to open MediaPicker getMedias with get videos option

```
2018-08-07 12:23:22.512811+0300 NTP Live[1292:547825] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'
*** First throw call stack:
```

I did a quick test, may be will test more and let you know

**Comment by DmcSDK** [comment]
@shajeeck  

I'm sorry that my code is rolled back. So it's not effective.

**Comment by shajeeck** [comment]
Since this crash only happens when there are no media folders or no media files in iphone, and chances for that are very less. I am not good at IOS native coding, or else would have submitted a PR.
Will patiently wait ...

**Comment by DmcSDK** [comment]
Have you tested the new version passed?

**Comment by shajeeck** [comment]
i will give it a try today and let you know, thanks!

**Comment by shajeeck** [comment]
@DmcSDK sorry for the delay!
I tested it and found that i am not getting any error when there is only one folder, case 1 is solved.
But when there is no media file to show it gives the same error as i mentioned as case 2. 

> When there are no videos in my iphone and i try to open MediaPicker getMedias with get videos option

To reproduce

1. set MediaPicker selection mode only video
2. open MediaPicker on an iphone emulator with no video files

it gives error  `[1292:547825] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'
*** First throw call stack:`

**Comment by DmcSDK** [comment]
@shajeeck  i fix no video file bug ，and i tested  it.
