### ISSUE TITLE
不能安装??

### ISSUE THREAD

**Issue by mixingyu** [DmcSDK/cordova-plugin-mediaPicker#37]
不知道为什么不能安装,本地安装可以 但是有个错误
![qq 20180908160451](https://user-images.githubusercontent.com/16440055/45251944-54396200-b381-11e8-83c7-51786f9d8639.png)
![qq 20180908160557](https://user-images.githubusercontent.com/16440055/45251945-57345280-b381-11e8-9be5-603db2d2573a.png)

**Comment by mixingyu** [comment]
小问题 自己修复了 :)

**Comment by DmcSDK** [comment]
@mixingyu  是什么问题啊，我感觉好像是我JAVA文件编译的错误，是我哪里写错了？因为我最新版本没有测试。

**Comment by DmcSDK** [comment]
@mixingyu 好的谢谢你修正了代码失误 我合并了。

**Comment by mixingyu** [comment]
@DmcSDK 哪里，也谢谢你的插件 ：）
