### ISSUE TITLE
I am unable to add this into my ionic Project, 

### ISSUE THREAD

**Issue by jaganreddy314** [DmcSDK/cordova-plugin-mediaPicker#39]

**Comment by jaganreddy314** [comment]
The error I am getting is * What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by DmcSDK** [comment]
Seems to be a duplicate jar package conflict
