### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by dodomui** [DmcSDK/cordova-plugin-mediaPicker#41]
I'm facing problem to use this library for IOS. Android is working properly.
MediaPicker v:2.3.0

1. After select a image / choose cancel in any IOS version, it will return to a blank screen, cannot see my app interface anymore.
I can see this warning from xcode after initiate media picker plugin.
`2018-09-20 22:29:06.803 [83080:25446518] Warning: Attempt to present <UINavigationController: 0x7fbea8029fb0> on <MainViewController: 0x7fbea5f59c90> whose view is not in the window hierarchy!`

2. Cannot preview in IOS8, after press preview receive below error.
![screen shot 2018-09-20 at 10 28 03 pm](https://user-images.githubusercontent.com/19356577/45825289-7d180a80-bd24-11e8-9cda-755a2722b8d0.png)
`2018-09-20 22:25:51.895 82981:25429629] -[UIButton widthAnchor]: unrecognized selector sent to instance 0x7fc38386dfc0
2018-09-20 22:25:51.898 [82981:25429629] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIButton widthAnchor]: unrecognized selector sent to instance 0x7fc38386dfc0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b830f35 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010b419bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010b83804d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010b79027c ___forwarding___ + 988
	4   CoreFoundation                      0x000000010b78fe18 _CF_forwarding_prep_0 + 120
	5   Wedding Self Checkin                0x0000000109cf55a8 -[PreviewViewController initView] + 1928
	6   Wedding Self Checkin                0x0000000109cf396e -[PreviewViewController viewDidLoad] + 190
	7   UIKit                               0x000000010c799a90 -[UIViewController loadViewIfRequired] + 738
	8   UIKit                               0x000000010c799c8e -[UIViewController view] + 27
	9   UIKit                               0x000000010c7bd507 -[UINavigationController _startCustomTransition:] + 633
	10  UIKit                               0x000000010c7c93fe -[UINavigationController _startDeferredTransitionIfNeeded:] + 386
	11  UIKit                               0x000000010c7c9f47 -[UINavigationController __viewWillLayoutSubviews] + 43
	12  UIKit                               0x000000010c90f509 -[UILayoutContainerView layoutSubviews] + 202
	13  UIKit                               0x000000010c6ed973 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 521
	14  QuartzCore                          0x000000010c500de8 -[CALayer layoutSublayers] + 150
	15  QuartzCore                          0x000000010c4f5a0e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 380
	16  QuartzCore                          0x000000010c4f587e _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	17  QuartzCore                          0x000000010c46363e _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 242
	18  QuartzCore                          0x000000010c46474a _ZN2CA11Transaction6commitEv + 390
	19  QuartzCore                          0x000000010c464db5 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 89
	20  CoreFoundation                      0x000000010b765dc7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	21  CoreFoundation                      0x000000010b765d20 __CFRunLoopDoObservers + 368
	22  CoreFoundation                      0x000000010b75bb53 __CFRunLoopRun + 1123
	23  CoreFoundation                      0x000000010b75b486 CFRunLoopRunSpecific + 470
	24  GraphicsServices                    0x000000010f73f9f0 GSEventRunModal + 161
	25  UIKit                               0x000000010c674420 UIApplicationMain + 1282
	26  Wedding Self Checkin                0x0000000109c8eb21 main + 65
	27  libdyld.dylib                       0x000000010ea50145 start + 1
	28  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by DmcSDK** [comment]
Q1:Should be in conflict with your other plugins, can you check out your list of plugins? Or try to remove other plugins and try again.
Q2：can't support IOS8.

**Comment by dodomui** [comment]
![screen shot 2018-09-21 at 3 08 56 pm](https://user-images.githubusercontent.com/19356577/45865507-52739380-bdb0-11e8-8185-1800628a01cc.png)
Here is my plugin list.

I will try to remove other plugins and see how.

Q2. Will you consider to hide the preview button for IOS8? because it will be a problem now while user click preview on IOS 8, else I think need use back image-picker for IOS8.

Thanks a lot.

**Comment by dodomui** [comment]
For Q1. Tried remove all other plugin... the problem still existed.
Actually I'm try to use mediapicker on several of my existing projects.

Most of them using the same plugin, but can run mediapicker without problem...
Not sure what's wrong with this app, cannot use mediapicker and imagepicker the rest plugin and function working just fine...

Any idea how could I identify the issue?

Thanks a lot if anyone can help.

**Comment by DmcSDK** [comment]
Let me see your AppDelegate.m code.

**Comment by dodomui** [comment]
```
#import "AppDelegate.h"
#import "MainViewController.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication*)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions
{
    self.viewController = [[MainViewController alloc] init];
    return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

@end

```

**Comment by DmcSDK** [comment]
This file looks normal，Tell me your ionic version。

**Comment by DmcSDK** [comment]
@dodomui have you solved this problem？
