### ISSUE TITLE
Several crash from some users who are using the app on android

### ISSUE THREAD

**Issue by ricardotera** [DmcSDK/cordova-plugin-mediaPicker#42]
This is the most frequent crash
![error3](https://user-images.githubusercontent.com/26750232/46177306-07f28b00-c278-11e8-88f1-70cdcd2ab1c0.PNG)

and these less often
![error1](https://user-images.githubusercontent.com/26750232/46177304-0759f480-c278-11e8-9019-cfd31a77a5da.PNG)
![error2](https://user-images.githubusercontent.com/26750232/46177305-07f28b00-c278-11e8-9768-85d2bf426380.png)
![error4](https://user-images.githubusercontent.com/26750232/46177618-2efd8c80-c279-11e8-9bb1-b82f26c356b3.PNG)

**Comment by DmcSDK** [comment]
thank you very much，i will fix it。

**Comment by DmcSDK** [comment]
I tried to fix the  less often bugs，you can test

**Comment by ricardotera** [comment]
Hi, thank u, let me build and update a new version of my app.

**Comment by DmcSDK** [comment]
I used maven to work with new android code.

**Comment by ricardotera** [comment]
Hello, the last 10 days was monitoring, and I can confirm that they did not happen again, the only crash that continues is the following
![4](https://user-images.githubusercontent.com/26750232/46832851-c4fee000-cd6c-11e8-80be-6dff2a782757.PNG)

**Comment by DmcSDK** [comment]
@ricardotera i fix the last bug ，you can test

**Comment by ricardotera** [comment]
ok thanks , I'm going to monitor it

**Comment by DmcSDK** [comment]
@ricardotera  sorry sir，This code version cannot be tested, he was restored to the old version

**Comment by DmcSDK** [comment]
@ricardotera sir , will the new version still crash？

**Comment by DmcSDK** [comment]
If it appears again, please reopen。
