### ISSUE TITLE
Failed to load image data for asset ... with format 9999

### ISSUE THREAD

**Issue by juliuskovac** [DmcSDK/cordova-plugin-mediaPicker#44]
When I use this plugin, sometimes I receive null object and I can see following error in Xcode console:

2018-10-11 13:43:21.794117+0200 App1[3420:921019] [Generic] Failed to load image data for asset <PHAsset: 0x15f4182d0> 111CA2A1-6D86-44F0-971C-D9C606BE23A6/L0/001 mediaType=1/4, sourceType=1, (2048x1536), creationDate=2016-03-16 15:06:23 +0000, location=0, hidden=0, favorite=0  with format 9999
2018-10-11 13:43:21.948760+0200 App1[3420:920711] (null)

Any idea how to solve this issue?

Thanks

**Comment by DmcSDK** [comment]
@juliuskovac Does this error often occur?

**Comment by DmcSDK** [comment]
in the new version，i tried fix this bug。

**Comment by juliuskovac** [comment]
@DmcSDK Thank you for update and sorry I didn't get to you sooner. We are still not sure why this error occur. We think it was happening for specific photos which ware older and get to the device through iCloud but turning it on and off wasn't solving the issue - probably they ware cached or something like that on device. We also try to search for this error and it seems there ware others experiencing same issue (eg. https://stackoverflow.com/questions/28170444/photos-framework-requestimagedataforasset-occasionally-fails) but I didn't completely understand what is cause of this issue so it may be better understood by someone with broader iOS knowledge.
