### ISSUE TITLE
Hope to have a open source License for this project

### ISSUE THREAD

**Issue by guoyongxin** [DmcSDK/cordova-plugin-mediaPicker#45]
MIT or Apache License 2.0

**Comment by DmcSDK** [comment]
这个许可怎么给你提供？

**Comment by DmcSDK** [comment]
@guoyongxin 你是需要这两个开源许可做什么呢？如果你知道流程可以告诉我一下我如何添加。

**Comment by guoyongxin** [comment]
写在项目Readme或者Code里都可以的，参考一下别的开源项目就好了。这样可以方便企业级的用户使用。
现在搞Cordova这种的人不多了吧。。不容易。。

**Comment by DmcSDK** [comment]
@guoyongxin 我加了个LICENSE 文件在项目里面，这样算是可以了吧？cordova国内搞这个的好像不多，国外感觉用的还蛮多的用的也多点，国内似乎喜欢用reactnative。
