### ISSUE TITLE
IOS 12 

### ISSUE THREAD

**Issue by a13720361433** [DmcSDK/cordova-plugin-mediaPicker#46]
I have a problem with this plugin in ios 12. I can' t obtain the image when I select an image.  It works well in any other version of ios . Do you have any way to solve this problem?

**Comment by DmcSDK** [comment]
@a13720361433  只有IOS 12无法选择图片吗？ 是12的第几个版本呢？我这边测试是没问题的。可以添加我的QQ 2286700982 详细联系。

**Comment by a13720361433** [comment]
iPhone5 ，ios 版本号12.0 16A366 使用这个插件可以选择图片，但是点击确认后就会报错。xcode上面调试了一下，没有获取到这个图片。

**Comment by DmcSDK** [comment]
@a13720361433  报的错误日志是什么呢，是所有照片都无法选择呢还是只有少数几张图片？

**Comment by a13720361433** [comment]
从新拍了一张图片可以获取到了，发现的确是之前选择的几张图都是存在icloud上面的图片。有没有什么方法能将icloud上图片获取到呢，或者能采取什么措施？因为都是在相册里面，有些图可以获取，有些图无法获取，感觉有些不太友好呢。

**Comment by DmcSDK** [comment]
@a13720361433 嗯好我调查调查

**Comment by DmcSDK** [comment]
@a13720361433 修复了你可以测试一下
