### ISSUE TITLE
Defect code for index use

### ISSUE THREAD

**Issue by guoyongxin** [DmcSDK/cordova-plugin-mediaPicker#50]
https://github.com/DmcSDK/cordova-plugin-mediaPicker/blob/8172f8194f757ef4f02f50507d173bcf9759166d/src/ios/DMCMediaPicker/DmcPickerViewController.m#L228

This line is using a NSInteger pointer which doesn't make any sense. Should pass the int directly to avoid the future defect. On line 225,
```
    [self show:0];
```
This is passing address 0 to the show function, And lucky converted to a int value as 0 which make it working good. But this code is not correct.

**Comment by DmcSDK** [comment]
thank
