### ISSUE TITLE
可否提供编译好的 jar包 放到 release 里面 谢谢

### ISSUE THREAD

**Issue by cybexr** [DmcSDK/cordova-plugin-mediaPicker#52]
可否提供编译好的 jar包 放到 release 里面 谢谢

**Comment by DmcSDK** [comment]
@cybexr  你需要这样做是有什么特别需求吗？ 安卓的源代码也在我的github 上，你可以按自己的需求来定制https://github.com/DmcSDK/MediaPickerPoject

**Comment by cybexr** [comment]
看到源码了谢谢，是直接下载到cordova-plugin-mediaPicker-dmcsdk\src\android 就可以吗? 用的IDE，不会用命令行的 麻烦了

**Comment by cybexr** [comment]
OK 非常感谢 我再研究下 gradle
