### ISSUE TITLE
Please what parameters/args is should be passed to the takePhoto() 

### ISSUE THREAD

**Issue by carter3rix** [DmcSDK/cordova-plugin-mediaPicker#56]
This is what i done so far similar to the one provided with cordova camera plugin but seems not to be working... But am able to take the new picture alright... Any assist... Thanks
`$scope.takeNewPicture = function(){
    
    var options = {
      allowEdit: true,
      encodingType: Camera.EncodingType.JPEG,
      targetWidth: 100,
      targetHeight: 100,
      popoverOptions: CameraPopoverOptions,
    };

    MediaPicker.takePhoto(options, function(picture){
      console.log(picture);
    });
  }`

**Comment by DmcSDK** [comment]
sorry takePhoto() support only android .

**Comment by DmcSDK** [comment]
@carter3rix  I am supporting this feature, the next version will be released
