### ISSUE TITLE
cordova  build ios error unrecognized platform name iOS

### ISSUE THREAD

**Issue by sdls10qq** [DmcSDK/cordova-plugin-mediaPicker#58]
cordova-plugin-mediapicker-dmcsdk/PreviewCell.m:22:24: error: unrecognized platform name iOS
cordova-plugin-mediapicker-dmcsdk/PreviewCell.m:23:32: error: property 'contentInsetAdjustmentBehavior' not
      found on object of type 'UIScrollView *'
            self.artScrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
                               ^
        platforms/ios/bcvet-cep/Plugins/cordova-plugin-mediapicker-dmcsdk/PreviewCell.m:23:65: error: use of undeclared identifier
      'UIScrollViewContentInsetAdjustmentNever'
            self.artScrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;

**Comment by DmcSDK** [comment]
please give me your xcode version and ios sdk version ,cordova version
