### ISSUE TITLE
Add german language support

### ISSUE THREAD

**Issue by Gkschd** [DmcSDK/cordova-plugin-mediaPicker#67]
ANDROID

><resources>
    <string name="library_name">MediaPicker</string>
    <string name="all_dir_name">Alle Bilder und Videos</string>
    <string name="all_video">Alle Videos</string>
    <string name="all_image">Alle Bilder</string>
    <string name="select_title">Wähle Bild und Video</string>
    <string name="select_video_title">Wähle Video</string>
    <string name="select_image_title">Wähle Bild</string>
    <string name="video_dir_name">Alle Videos</string>
    <string name="msg_amount_limit">Maximale Anzahl erreicht</string>
    <string name="msg_size_limit">Die maximale Dateigröße ist</string>
    <string name="select_null">Bitte wähle eine Datei</string>
    <string name="done">Fertig</string>
    <string name="count_string"></string>
    <string name="preview">Vorschau</string>
    <string name="select">Auswahl</string>
    <string name="video">Video</string>
    <string name="cant_play_video">Kein Abspiel-Programm!</string>
    <string name="READ_EXTERNAL_STORAGE">Lese-Berechtigung wird benötigt</string>
</resources>

IOS

"Cancel"="Abbrechen";
"Done"="Fertig";
"Back"="Zurück";
"All"="Alle Fotos";
"Video"="Video";
"maxSelectAlert"="Maximale Anzahl erreicht";
"ok"="OK";
"Unable to access album" = "Auf Album kann nicht zugegriffen werden";
"Please allow to access your album" = "Bitte erlaube den Zugriff auf Dein Album in "Einstellungen -> Datenschutz -> Fotos"";
"Setting" = "Einstellungen";
"Preview" = "Vorschau";

**Comment by DmcSDK** [comment]
@Gkschd ok
