### ISSUE TITLE
App crashed when no pics/video in my album

### ISSUE THREAD

**Issue by imgoddqp** [DmcSDK/cordova-plugin-mediaPicker#68]
Thanks a lot for this amazing plugin first.
now we buy a new iphone xr for test，we met some trouble:
1. When there was no photos or videos in the album, the plug-in will crash. Choosing an empty album without videos or photos will also cause errors.
2.There was no response when choosing the video, and the background reported compress failed. No problem with other iPhone models. I  see other issues, he said that video could not be selected on the simulator. You responded that it was slow to switch to mp4. Is that the reason? Then can we not transcode it? We have transcoding service in the backend.

may i speak chinese?yes...

很感谢这款帅气碉堡的插件。
我们在用iphone xr测试的时候遇到了这么几个问题：
1. 当相册里没有照片、视频的时候，插件会崩溃。选择一个没有视频、照片的空相册也会报错。
2. 选择视频的时候没反应，后台报错说compress failed。其他iphone机型没问题。我看了其他的issue，有个哥们说在模拟器上不能选视频，您给回复说要转mp4所以慢。是这个原因吗？那么能不转码吗？我们后台有转码的服务。

**Comment by DmcSDK** [comment]
@imgoddqp 
1.我尝试了下把一个相册照片清空，没有出现这个情况。如果方便的话您可以把手机插到Xcode上看看具体的错误日志是什么。
2.当选择比较大的视频时的确会比较慢，因为要转换成MP4，当然我没有遇到过失败的情况，也许是什么特殊情况造成的，抱歉暂时不支持不转码选项，这个地方有点小复杂，因为文件必须移动到IOS沙盒下才能操作。

**Comment by imgoddqp** [comment]
很激动大神能回复我，非常感谢！我删了所有的视频，然后选择视频的时候，默认进来了“最近删除”，这时候我尝试选择其他相册的时候，就crash了。堆栈信息如下：

![image](https://user-images.githubusercontent.com/24971545/54419017-684f8900-4741-11e9-89e9-96ea62609463.png)

**Comment by imgoddqp** [comment]
@DmcSDK  请问能否提供一些帮助呢？我可以向公司申请红包O(∩_∩)O，我的qq 529681126
