### ISSUE TITLE
Unable to select photos in iPad

### ISSUE THREAD

**Issue by Mr-Anonymous** [DmcSDK/cordova-plugin-mediaPicker#71]
Some users using ipad say that they get the message 'unable to obtain pictures' and cannot upload the photos. It works fine in my iPad testings. But its a small percentage of users who seem to have this issue. Here is one such report:

> OS: ios 12.1.4 
> Browser: unknown 0 
> Device: ipad 
> 
> I keep getting an ‘unable to obtain photos message’.  I’ve tried logging out and back in and reducing to only a couple of photos, but still no luck.  It is often an issue but will usually let me upload if I log out then back in again.  This time it is still not uploading any photos.

  

What could be the reason in such cases? Is this something related to MediaPicker or FileTransfer plugin?

This is how I process the mediapicker selections:

```
              var options = {
                    quality: 50,
                    destinationType: Camera.DestinationType.FILE_URI,
                    sourceType: Camera.PictureSourceType.PHOTOLIBRARY,
                    encodingType: Camera.EncodingType.JPEG,
                    mediaType: Camera.MediaType.PICTURE,
                    targetWidth: 1800,
                    targetHeight: 1200,
                    correctOrientation: true
              }
              
              var server = 'xyz-url';
              var mime = "image/jpeg"; 
              
              var args = {
                    'selectMode': 100, //101=PICKER_IMAGE_VIDEO , 100=PICKER_IMAGE , 102=PICKER_VIDEO
                    'maxSelectCount': 30, //default 40 (Optional)
              };

              MediaPicker.getMedias(args, function(results) {
                  if (results.length) {
                  	// process Image Picker On Success for uploading
                  	// using loop through images and compress image
                  	// before uploading using file transfer
                  }
                  else {
                    deferred.reject(null);
                  }
              }, function (error) {
                    // console.log('Error: ' + error);
                    alert("Unable to obtain pictures");
                    deferred.reject(error);
              });
```
              
This is my app environment:
```      
code-push 2.0.4 "CodePushAcquisition"
cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
cordova-plugin-appcenter-analytics 0.1.4 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.1.4 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.1.3 "App Center shared code for Cordova"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-code-push 1.11.10 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-mediapicker-dmcbig 2.3.8 "MediaPicker"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
Ionic info:

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    Cordova Platforms : android 7.0.0 ios 4.5.5
    Ionic Framework   : ionic1 1.3.3

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v9.3.0
    npm        : 5.7.1 
    OS         : macOS
    Xcode      : Xcode 10.1 Build version 10B61 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro              
```

**Comment by DmcSDK** [comment]
@Mr-Anonymous  Maybe your user has denied permission？
Privacy - Photo Library permission

**Comment by Mr-Anonymous** [comment]
Hi @DmcSDK 

No. User said she uninstalled and reinstalled it again and she also allowed permission. She says it works sometimes and sometimes it doesn't work. 

```
is your user see this alert？"alert("Unable to obtain pictures");"
```
Yes. thats the error she said and it appears its failing on `MediaPicker.getMedias()`.

**Comment by DmcSDK** [comment]
@Mr-Anonymous  can you get  this  error  `// console.log('Error: ' + error);`

**Comment by Mr-Anonymous** [comment]
Sorry @DmcSDK  I completely understand its almost impossible to fix something without knowing the error. I have the same trouble too since I could not replicate it and none of the diagnostics report has log on this error. Unfortunately, this user had cancelled her app subscription now and I am unable to follow up further on this. Similar to this, 2 other users had also reported the same issue in the past few months and they all were using iPad. Its difficult cuz none of them replied to my queries asking for more info.

If I gather any more info in the future, I will let you know. As of now, it seems I have reached a dead end and hopefully someone with more info can contact me in the future.

**Comment by DmcSDK** [comment]
@Mr-Anonymous  sorry

**Comment by Mr-Anonymous** [comment]
Quick Question: Another user who subscribed to my app today using ipad reported the same problem today. I am now going to release an app update that logs the error exception into my database so we can catch the error. How do I add that? I mean, does the below code send the data as json encoded? Do you have a sample on how an error data might look so I can configure my backend php to expect such a data structure?

```
function cameraError(error) {
                  // console.debug("Unable to obtain picture: " + error, "app");
                  alert("Unable to obtain picture");
                  deferred.reject(error);
                 var errorMessage = { errorLog : error };
                 // Log to server 
                databaseLogService.logError(errorMessage);
              }, options);
```

The service is something like this:

```
function logError (  errorMessage ) {
            return $http({
                method	: 'POST',
                url		: endpoint.url,
                data		: $.param(  errorMessage ),
                headers : { 'Content-Type': 'application/x-www-form-urlencoded' }
            });
        }
```

I am using Angular 1.5 and my backend is using Laravel where I get the errors like this in the php controller:
```
$postData = $request->only('errorLog');
// Insert this entry into database: $postData['errorLog'];
```

Does the `$postData['errorLog']` received by php is in json encoded format? I can just insert the entire content into a sql column set as longtext or string perhaps?

**Comment by DmcSDK** [comment]
@Mr-Anonymous  the error is a string。

@guoyongxin 你好请教你一个问题，上面这位开发者的总是在ipad ios 12.1.4上出现问题，问题似乎是在MediaPicker.m的 imageToSandbox方法的85行写入沙盒触发错误回调函数，ipad在这上面有什么特殊性吗？

**Comment by Mr-Anonymous** [comment]
thanks for that. I am right now updating my app with this.

**Comment by Mr-Anonymous** [comment]
Ok. I have added the patch to insert error log into the database, for testing how can I fake an error to check if the patch is working properly? I uninstalled and reinstalled the app, decline the gallery permission and tried to add an image but that did not throw an error. How can I test to see if the error is getting posted to the database before I release this update to the production app?

**Comment by DmcSDK** [comment]
@Mr-Anonymous quite difficult test，The storage space is full or the stored folder does not exist well trigger the error.

**Comment by Mr-Anonymous** [comment]
@DmcSDK Thank you for the update and I apologise for the inconvenience. If its those cases, how can they resolve it? Does it mean they need to uninstall and reinstall the app? Is it the device storage full or does each app has a limit on its app storage? How do I troubleshoot these users?

**Comment by DmcSDK** [comment]
@Mr-Anonymous  change ios MediaPicker.m code,`[imageData writeToFile:fullpath options:NSAtomicWrite error:&error]` to `[imageData writeToFile:@"testtest/tttt/ttt/tldll/d" options:NSAtomicWrite error:&error]`

**Comment by Mr-Anonymous** [comment]
Hi @DmcSDK I updated my app so if there is an error, the app logs an entry of the error message to my database so I can get that. Since the app was updated, so far I have 2 entries but none of them as the `error` messages. They show up empty. This only happens for the error exception thrown by Mediapicker since all other error messages are getting recorded.

This is how I have it set-up in the app:

```
MediaPicker.getMedias(args, function(results) {
                  if (results.length) {
                    // Process the upload
              }, function (error) {
                    // console.log('Error: ' + error);
                    alert("Unable to obtain pictures");
                    // Log Error
                    var errorLogPost = {
                        userId        : user.id,
                        version       : config.appVersion,
                        source        : 'Mobile App',
                        uploadMethod  : user.uploadMethod,
                        os            : deviceDetector.os + ' ' + deviceDetector.os_version,
                        browser       : deviceDetector.browser + ' ' + deviceDetector.browser_version,
                        device        : deviceDetector.device,
                        location      : 'MediaPicker.getMedias() function (error)',
                        exception     : error
                    };
                    databaseService.logError(errorLogPost);
                    deferred.reject(error);
              });
```

Here, I am using the `deviceDetector` plugin to record more information about the device. However, when the error is logged in the database, it is empty.

![Screenshot 2019-03-21 at 6 39 12 PM](https://user-images.githubusercontent.com/8770270/54754385-67b76680-4c09-11e9-889e-abe6002689b2.png)

I was hoping to catch the error after the update, but this happens so not sure what is causing the error exception in these cases. However, these 2 users have not yet contacted me reporting about the error and I only know about it after the database entries. Any ideas? Could these be due to error or is it due to some other actions?

**Comment by Mr-Anonymous** [comment]
Today I had 7 error logs from my user devices and all had empty messages for `error`.

![Screenshot 2019-03-22 at 12 45 00 PM](https://user-images.githubusercontent.com/8770270/54806669-b8c66980-4ca0-11e9-8007-0dcf0ee65096.png)

**Comment by DmcSDK** [comment]
@Mr-Anonymous  i  change ios MediaPicker.m code,
`[imageData writeToFile:fullpath options:NSAtomicWrite error:&error] `
to 
`[imageData writeToFile:@"testtest/tttt/ttt/tldll/d" options:NSAtomicWrite error:&error]`

and test  alert（error） is work 

```
MediaPicker.getMedias(args, function(results) {

              }, function (error) {
                   alert（error）；
              });
```

**Comment by Mr-Anonymous** [comment]
Sorry, do i just edit the `MediaPicker.m` file and recompile it or do I update the cordova plugin?

And, can I add this edit to my production app so I can gather the error from my live users? Or is it only for my local testing purpose?

Let me know soon if possible so I can update my app today. Thank you @DmcSDK

**Comment by DmcSDK** [comment]
@Mr-Anonymous to local testing purpose。

**Comment by Mr-Anonymous** [comment]
ok, what do I do to add this to the production app so the errors are not empty and are logged in DB? In local testing,I am unable to replicate these issues users are having where as the production app `MediaPicker` logs empty errors. So, how do I add this update to my production app so I can track the errors happening to my users and not have empty error messages?

**Comment by DmcSDK** [comment]
@Mr-Anonymous You tested locally, is the error string a data pair?

**Comment by Mr-Anonymous** [comment]
@DmcSDK I am still stuck on this and I dont know what I can do from my end. I could not replicate any errors so how can I test ur previous code offline? I did try to edit `MediaPicker.m` file and made the edit to `[imageData writeToFile:fullpath options:NSAtomicWrite error:&error] `  but when I test it offline, I dont get errors cuz the plugin picks the images so I dont know what the output of `alert(error)`. In the meantime, I am getting over 10 errors logged everyday in my production mobile app and its from users using iPads. All of them with empty `error`. I dont know what else I can do from my end here.

**Comment by DmcSDK** [comment]
@Mr-Anonymous First change the MediaPicker.m code, then test it on your own ipad, alert when it encounters an error, and try uploading it to your error collection to test.
If you can alert the error message, I suspect that your error collection program may have a problem.

**Comment by Mr-Anonymous** [comment]
Thats the problem. I have already done these:

1.  edited the iOS MediaPicker.m code

2. Added `alert(error)` to my code for error method

3. Tested it on my iPad.

But, I dont get any errors in my ipad. When I select the image, it gets uploaded fine and therefore the  `function (error){}` is not even triggered. How can I test the error alert if I can't replicate an error?

**Comment by DmcSDK** [comment]
@Mr-Anonymous  If you modify it according to my code, it is absolutely impossible to run normally, because this code will cause the plugin to cause an error. When the click is completed, the error will be triggered directly and the alert will be displayed.
You should be modifying the file incorrectly, try to download my plugin locally, then modify the local plugin, then uninstall the test project plugin, install the local plugin

**Comment by Mr-Anonymous** [comment]
Thanks for clarifying that @DmcSDK I tried rebuilding 3 times today after editing the file. I will remove and re-add the plugin and platforms again and try to build it. Or edit the local plugin like u said. Will report back with the update.

**Comment by DmcSDK** [comment]
@Mr-Anonymous First you need to let me modify the test error code, alert information on the ipad

**Comment by Mr-Anonymous** [comment]
Ok. Here is an update. 

1. Making your suggested edit to the test plugin throws the alert: `The folder "d" doesn't exist`.

2. Also, this error message got inserted to the database just fine and I did not make any changes to the backend script. 

So it means, the error collection is working fine. But this now comes back to the original question on why does all other error entries that gets logged has empty string for  `error`. Which means, these users are getting some exception thrown with empty `error`. Attached is the production database table screenshot.

![Screenshot 2019-04-01 at 2 49 47 PM](https://user-images.githubusercontent.com/8770270/55317571-6817f300-548e-11e9-92e0-a96a97c8bd24.png)

**Comment by Mr-Anonymous** [comment]
Today I got a few entries some with empty error and some with the following error message, it probably what you identified from your testing before:

```
You can’t save the file “AF66C944-XXXX-XXXX-XXXX-A25D8D09D374-XXX-000002A9D60974BAIMG_5239.JPG” because the volume “/” is out of space.
```

How do I resolve this? Does it mean their iPad is out of space or is my app folder's storage is out of space? If its my app's storage folder, how much space is usually allocated for this?

**Comment by DmcSDK** [comment]
@Mr-Anonymous can you tell me your APP name？

**Comment by DmcSDK** [comment]
@Mr-Anonymous cordova-plugin-mediapicker-dmcbig 2.3.8 "MediaPicker"  is Obsolete plugin，
cordova-plugin-mediapicker-dmcsdk 2.4.5 is new plugin

**Comment by Mr-Anonymous** [comment]
@DmcSDK V sorry for the delay in my reply. Ok, I will update my plugin to 2.4.5 and see how that goes. Currently working on a big release on this app which is scheduled to be released in 2 weeks so I will add this 2.4.5 plugin with that update.

**Comment by Mr-Anonymous** [comment]
Hi @DmcSDK I updated my app with the recent version of this plugin about 10 days ago and so far I have not received the error logs with empty exception messages that I reported earlier. However today I got an error log with the following message:

```
You can’t save the file “06490467-220C-4E83-859D-28A02ECD7F35-3011-000000BQS5274A33IMG_9595.JPG” because the volume “/” is out of space.
```

It was from iPad with ios 12.2.

What do they need to do to resolve this? Do they need to uninstall and reinstall the app? whats the cause for this? Is it the application storage being full?

**Comment by DmcSDK** [comment]
@Mr-Anonymous 
The files created by my plugin are temporary.
https://developer.apple.com/documentation/foundation/1409211-nstemporarydirectory
`    NSString * tmpDir = NSTemporaryDirectory();
    NSString *dmcPickerPath = [tmpDir stringByAppendingPathComponent:@"dmcPicker"];`
So this has nothing to do with the plugin，The reason for this problem is that the user's mobile phone storage is full.
https://discussions.apple.com/thread/250163708
So how to solve it? Can only prompt the user to delete some files

**Comment by Mr-Anonymous** [comment]
Awesome. Thank you for clarifying this for me. 

I love your plugin and most importantly, your support is excellent.

**Comment by DmcSDK** [comment]
@Mr-Anonymous Has this problem recently occurred?

**Comment by Mr-Anonymous** [comment]
Hi @DmcSDK I havent had error exceptions being logged after the last update of this plugin. So far, users have not contacted me about this issue since the update about a month ago. You can close this issue if you want and if I have any trouble related to this again, I will follow up. 

Thank you @DmcSDK
