### ISSUE TITLE
maxSelectSize not working

### ISSUE THREAD

**Issue by 2xSamurai** [DmcSDK/cordova-plugin-mediaPicker#73]
Hello. 
Firstly thank you for the plugin. It's great.

maxSelectSize is not working. Even if I specify a smaller size, nothing happens. Can you please check.

Also, can you also add the file size property to video file Array?

Thank you.

**Comment by DmcSDK** [comment]
@2xSamurai  sorry ! ios can not support maxSelectSize args.

**Comment by 2xSamurai** [comment]
@DmcSDK Oh I see. Thank you for the quick response. Any way I can get the file size of the file after I select it?

**Comment by DmcSDK** [comment]
@2xSamurai 
maybe this code will help you。
`MediaPicker.getMedias(args, function(medias) {
        var media=medias[0];
        var size=media.size;
}`

**Comment by 2xSamurai** [comment]
@DmcSDK 

Ok, Thank you very much. I think the size is not there for vides though. 
I am closing the thread. 
Again thank you very much for the plugin.
