### ISSUE TITLE
Version 2.4.5 has build error in Android

### ISSUE THREAD

**Issue by Mr-Anonymous** [DmcSDK/cordova-plugin-mediaPicker#75]
Hi @DmcSDK 

I updated this plugin from version 2.3.8 to version 2.4.5, but after the update I am unable to build my app for Android. It works fine for iOS build but when I try `ionic cordova build android`, I get the following exception:

```
BUILD FAILED in 1m 1s
28 actionable tasks: 5 executed, 23 up-to-date
(node:28598) UnhandledPromiseRejectionWarning: Error: /Users/neel/Sites/app-mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/neel/Sites/app-mobile/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:262: error: cannot find symbol
                file=new File(FileHelper.getRealPath(args.getString(0),cordova));
                              ^
  symbol:   variable FileHelper
  location: class MediaPicker
/Users/neel/Sites/app-mobile/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:271: error: cannot find symbol
            String mimeType = FileHelper.getMimeType(jsonObject.getString("uri"),cordova);
                              ^
  symbol:   variable FileHelper
  location: class MediaPicker
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by DmcSDK** [comment]
@Mr-Anonymous oh sorry sir [https://www.npmjs.com/settings/dmcbig/packages](url) This dmcbig 2.4.5 version is no longer maintained.
you need install plugin for github

**Comment by Mr-Anonymous** [comment]
Thank you so much for that @DmcSDK Installing the package from github link works. It took a while to download the package, maybe due to its size or slow internet connectivity, not sure, but it works and I am not able to build both iOS and Android apps with this current version from github.
