### ISSUE TITLE
ionic3 error build in ios 

### ISSUE THREAD

**Issue by he429134733** [DmcSDK/cordova-plugin-mediaPicker#76]
at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modu
les\_cordova-lib@8.1.1@cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordo
va\node_modules\_q@1.5.1@q\q.js:854:54)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\cordova\node_modu
les\_q@1.5.1@q\q.js:883:30
Uh oh!
File already exists at destination "G:\cunmai\platforms\ios\存脉\Resources\de.lp
roj" for resource file specified by plugin cordova-plugin-telerik-imagepicker in
 iOS platform
    at Promise.promise.promiseDispatch (C:\Users\Administrator\AppData\Roaming\n
pm\node_modules\cordova\node_modules\_q@1.5.1@q\q.js:816:13)
[ERROR] An error occurred while running subprocess cordova.

        cordova platform add ios --save exited with exit code 1.

        Re-running this command with the --verbose flag may provide more
        information.

Android is normal but build ios4.5.5 is wrong

**Comment by DmcSDK** [comment]
@he429134733 插件有同名文件冲突，cordova-plugin-telerik-imagepicker 这个插件里面有个de.lproj文件，我的插件也有这文件，如果你是测试的插件的话，建议你卸载cordova-plugin-telerik-imagepicker 再试吧。

**Comment by he429134733** [comment]
thank u
