### ISSUE TITLE
embedded creation date problem for video under iOS

### ISSUE THREAD

**Issue by whisere** [DmcSDK/cordova-plugin-mediaPicker#77]
Hello, after selecting a file and uploading it to server, the embedded creation date of the video is changed for the one uploaded under iOS, the creation date is changed to the time the file is uploaded, however in Android, this works correctly, the embedded creation date of the video remains as when the video is taken. For photo it works correctly under both iOS and android. I think In iOS a temporary file is created for access, I wonder what the difference between image and video processes is, so the embedded creation date of image remain as when the photo is taken while that of video is changed? Any idea is much appreciated.

**Comment by DmcSDK** [comment]
@whisere sorry Converting MP4 caused date change

**Comment by whisere** [comment]
@DmcSDK Thanks for the reply. Is it possible to upload the original file? and does the MP4 convert process reduce the quality of the video? Any way to transfer the date to the MP4 too? Many thanks!

**Comment by DmcSDK** [comment]
@whisere how do you get the creation date?

**Comment by whisere** [comment]
@DmcSDK we get it from solr index via apache tika, it can also be extracted from exiftool http://owl.phy.queensu.ca/~phil/exiftool/

**Comment by whisere** [comment]
@DmcSDK I tried to import both the original mov file and the transferred mp4 file into Photo on Mac, found the mp4 file quality is much lower than the original mov file, eg resolution was 1080*1920 for mov (6.6mb), 320*568 for mp4 (338kb), camera and len etc metadata information are also missing from the mp4 file, is it possible to upload the original mov file instead, we can transfer to mp4 at the server side or keep the quality, resolution and metadata in the mp4 file during the transfer while upload?

**Comment by DmcSDK** [comment]
@whisere change source code mediapick.m file `AVAssetExportPresetMediumQuality` to `AVAssetExportPresetHighestQuality `

**Comment by whisere** [comment]
@DmcSDK Thanks! will try that.

**Comment by whisere** [comment]
@DmcSDK I have tried to change the quality from medium to highest as you suggested above. The MP4 quality has improved to the same as the original. Thank you!

But the metadata for camera, len is still missing and creation date metadata is still incorrect, so I tried the below change on mediapick.m to upload the MOV instead of the transferred MP4. It seems working and the metadata are correct. Do you have any suggestions on the change or will that cause any problems?

I changed videoToSandboxCompress to videoToSandbox on line
[self videoToSandboxCompress:asset dmcPickerPath:dmcPickerPath aListArray:aListArray selectArray:selectArray index:index];

Commented out the first 7 line in function videoToSandbox
and change options:options to options:nil on the 8th line.

Many thanks!

**Comment by DmcSDK** [comment]
@whisere it look right, is work ok?

**Comment by whisere** [comment]
@DmcSDK It seems working find so far, I will do more testing later and let you know. Thank you.

**Comment by DmcSDK** [comment]
@whisere I don't think you need to remove the code from 1 to 7 lines.  the code use download by icloud file。

**Comment by whisere** [comment]
@DmcSDK I won't have access to the code until next week, but I tried it before, If I don't remove the first 7 lines of function videoToSandbox I get error from the code, I was uploading mov file from ios. Something to do with the PHImageRequestOptions variable can't be found I think. I don't quite get what you mean by 'the code use download by icloud file'? Thanks.

**Comment by DmcSDK** [comment]
@whisere  download file by icloud

**Comment by whisere** [comment]
@DmcSDK Thanks, I tried to run it again, it seems the error disappears, if it happens again I am thinking adding the condition for options like this:
PHImageRequestOptions *options = [[PHImageRequestOptions alloc] init];
    **if(options!=nil){**
        options.networkAccessAllowed = YES;
        options.resizeMode = PHImageRequestOptionsResizeModeFast;
        options.progressHandler = ^(double progress, NSError *error, BOOL *stop, NSDictionary *info) {
            NSString *compressCompletedjs = [NSString stringWithFormat:@"MediaPicker.icloudDownloadEvent(%f,%i)", progress,index];
            [self.commandDelegate evalJs:compressCompletedjs];
        };
    **}**
    [[PHImageManager defaultManager] requestAVAssetForVideo:asset options:options resultHandler:^(AVAsset *avsset, AVAudioMix *audioMix, NSDictionary *info) {
