### ISSUE TITLE
当iphone xs 的时候，有些图片选择出错。。。

### ISSUE THREAD

**Issue by he429134733** [DmcSDK/cordova-plugin-mediaPicker#78]
![image](https://user-images.githubusercontent.com/44768024/57190859-d3ebf080-6f51-11e9-8287-c47aa7487360.png)

选取之后：
![image](https://user-images.githubusercontent.com/44768024/57190863-da7a6800-6f51-11e9-98ae-6e76db6f23e6.png)

奇怪的时，这部手机有的图片选取是没问题的，有些图片选取就会变成这样。并且不能进行下一步操作。

**Comment by he429134733** [comment]
![image](https://user-images.githubusercontent.com/44768024/57190891-44930d00-6f52-11e9-850c-41b7fb4c7d21.png)
这是tongyibu同一部选取正常的样子，他可以进行下一步操作

**Comment by he429134733** [comment]
这部手机的不可选取的图像后缀的HEIC

**Comment by DmcSDK** [comment]
@he429134733 是heic格式的问题吗？

**Comment by he429134733** [comment]
是的，heic 格式只有ios11以上才支持，大内存的图片苹果是用heic储存的，需要把他转换成png的，因为heic不能在win，android，甚至一些低版本的ios上查看，因为不兼容，不知道能否吧这个格式的图片转成jpg或者png的。。。。

**Comment by DmcSDK** [comment]
@he429134733 compressImage 方法会转换格式

**Comment by he429134733** [comment]
不行哦，用了这个函数，图片的后缀还是heic

**Comment by he429134733** [comment]
![image](https://user-images.githubusercontent.com/44768024/57205233-b66d6400-6fef-11e9-95a9-0278ae704bad.png)

**Comment by he429134733** [comment]
![image](https://user-images.githubusercontent.com/44768024/57205244-cdac5180-6fef-11e9-807e-9e770b45abf4.png)

**Comment by DmcSDK** [comment]
@he429134733  参数quality必须小于100

**Comment by he429134733** [comment]
好的，牛逼呀！

**Comment by DmcSDK** [comment]
@he429134733 现在功能OK了吗

**Comment by he429134733** [comment]
ok了，没问题了

**Comment by he429134733** [comment]
牛逼，happy code！

**Comment by he429134733** [comment]
牛逼 。happy coding！！！
