### ISSUE TITLE
"compress failed" Error in iOS 

### ISSUE THREAD

**Issue by Mr-Anonymous** [DmcSDK/cordova-plugin-mediaPicker#80]
Sometimes, I get the `compress failed` error exception. I have set-up my app to email me the exception log if any of my user have issues when using the mediapicker plugin. One of my user seems to be having this error. Below is her device details:

>>>
Device: iPhone
OS: iOS 12.3.1
Error Location: MediaPicker.getMedias() function (error)
Exception: compress failed
>>>

Below is my code:

```
	  MediaPicker.getMedias(args, function(results) {
                  if (results.length) {
                   .......
                  }
                  else {
                    deferred.reject(null);
                  }
              }, function (error) {
                    // console.log('Error: ' + error);
                    var errorMessage = (error) ? error : 'Unable to obtain pictures';
                    alert(errorMessage);
                    service.length = 0;
                    // Log Error
                    var errorLogPost = {
                        source        : 'Mobile App',
                        uploadMethod  : user.uploadMethod,
                        os            : deviceDetector.os + ' ' + deviceDetector.os_version,
                        browser       : deviceDetector.browser + ' ' + deviceDetector.browser_version,
                        device        : deviceDetector.device,
                        location      : 'MediaPicker.getMedias() function (error)',
                        exception     : error
                    };
                    consoleService.logError(errorLogPost);
                    deferred.reject(error);
              });
```
![Screenshot 2019-07-17 at 10 04 38 AM](https://user-images.githubusercontent.com/8770270/61347590-282d1e00-a87b-11e9-8590-155af5bc7f19.png)

Below is my ionic info:

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    Cordova Platforms : android 7.0.0 ios 4.5.5
    Ionic Framework   : ionic1 1.3.3

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v11.12.0
    npm        : 5.7.1 
    OS         : macOS
    Xcode      : Xcode 10.1 Build version 10B61 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

Here are my plugins list and the version:
```
code-push 2.0.6 "CodePushAcquisition"
cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
cordova-plugin-appcenter-analytics 0.1.4 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.1.4 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.1.3 "App Center shared code for Cordova"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-code-push 1.11.15 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-mediapicker-dmcsdk 2.4.5 "MediaPicker"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.7 "OneSignal Push Notifications"
```

What could cause this compress failed error message?

**Comment by Mr-Anonymous** [comment]
The user contacted us regarding this issue and here is more info on her trouble:

>>>
Yesterday a video of 22 secs uploaded fine. The video I am trying to upload is only 20secs long.  Have just tried to upload other videos and they seem to work fine. Not sure what the problem is with this video. 
>>>

**Comment by DmcSDK** [comment]
@Mr-Anonymous  Is this error appearing on many users' phones? Still only one or a few users?

**Comment by Mr-Anonymous** [comment]
Sorry for my late reply. I completely missed this one. This error so far has only happened to 2 users. One user was last month which I ignored since that was the first time I saw the error, then the second one recently. The user said she was having issue with only 1 video and rest seems to upload fine. I then asked her to try uploading that video from the web app using chrome and the upload worked fine in chrome.

So yeah, its not a common problem. Only happened to couple of users so far and thought I will just let you know incase. If it happens again to anyone else, I will surely update it here.

Thank you @DmcSDK

**Comment by Mr-Anonymous** [comment]
Soon after my posted my last comment, I got another error log entry with the same message from a different user. This is the user's device info I can gather so far from the log:
>>>
Device: ipad
OS: ios 12.3.1
Error: compress failed
>>>

**Comment by DmcSDK** [comment]
@Mr-Anonymous  this 2.4.5 "MediaPicker" ，very Sorry,this version of the error log is not perfect, you may want to upgrade to the new version via git. I can see the real error details

**Comment by Mr-Anonymous** [comment]
Thanks @DmcSDK . I will update this plugin in the next release and keep you posted.
