### ISSUE TITLE
2.4.7 is not available in npm

### ISSUE THREAD

**Issue by mmartinez** [DmcSDK/cordova-plugin-mediaPicker#97]
Can we get an update of the latest release in npm?

Thanks for the great plugin :)

**Comment by ryaa** [comment]
We really need to improve this plugin npm packaging handling - https://github.com/DmcSDK/cordova-plugin-mediaPicker/issues/93

**Comment by mmartinez** [comment]
Maybe we can setup CI/CD? I'd be nice to automate it. I'd be willing to help if necessary :)
