### ISSUE TITLE
Language as option

### ISSUE THREAD

**Issue by ehdez82** [DmcSDK/cordova-plugin-mediaPicker#98]
Greetings, is it possible to send the language as an option to the getMedias function? Thank you.

**Comment by ehdez82** [comment]
Any possibility with including this option?

**Comment by Scobee** [comment]
@ehdez82 did you figure out how to send the function ? currently my language is turkish, or something

**Comment by ehdez82** [comment]
@Scobee I could not. The plugin takes the language configured on the device.
