### ISSUE TITLE
Version 2.4.7 has build error in Android

### ISSUE THREAD

**Issue by LucaTrip** [DmcSDK/cordova-plugin-mediaPicker#99]
I installed the lastest version from `cordova plugin add https://github.com/DmcSDK/cordova-plugin-mediaPicker.git` and during the `ionic cordova build android` it has the following errors:

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:14: error: package com.dmcbig.mediapicker does not exist
import com.dmcbig.mediapicker.PickerActivity;

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:15: error: package com.dmcbig.mediapicker does not exist
import com.dmcbig.mediapicker.PickerConfig;

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:16: error: package com.dmcbig.mediapicker does not exist
import com.dmcbig.mediapicker.TakePhotoActivity;

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:17: error: package com.dmcbig.mediapicker.entity does not exist
import com.dmcbig.mediapicker.entity.Media;

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:78: error: cannot find symbol TakePhotoActivity
        Intent intent =new Intent(cordova.getActivity(), TakePhotoActivity.class); 

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:84: error: cannot find symbol PickerActivity
        Intent intent =new Intent(cordova.getActivity(), PickerActivity.class);

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:85: error: cannot find symbol PickerConfig
        intent.putExtra(PickerConfig.MAX_SELECT_COUNT,10); 

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:94: error: cannot find symbol PickerConfig
                intent.putExtra(PickerConfig.SELECT_MODE,jsonObject.getInt("selectMode"));

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:99: error: cannot find symbol PickerConfig
                intent.putExtra(PickerConfig.MAX_SELECT_SIZE,jsonObject.getLong("maxSelectSize")); 

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:104: error: cannot find symbol PickerConfig
                intent.putExtra(PickerConfig.MAX_SELECT_COUNT,jsonObject.getInt("maxSelectCount"));

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:109: error: cannot find symbol Media
                ArrayList<Media> select= new ArrayList<Media>();

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:109: error: cannot find symbol Media
                ArrayList<Media> select= new ArrayList<Media>();

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:112: error: cannot find symbol Media
                    select.add(new Media(jsonArray.getString(i), "", 0, 0,0,0,""));

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:114: error: cannot find symbol PickerConfig
                intent.putExtra(PickerConfig.DEFAULT_SELECTED_LIST,select); // (Optional)

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:158: error: cannot find symbol PickerConfig
            if(requestCode==200&&resultCode==PickerConfig.RESULT_CODE){

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:159: error: cannot find symbol Media
                final ArrayList<Media> select=intent.getParcelableArrayListExtra(PickerConfig.EXTRA_RESULT);

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:159: error: cannot find symbol PickerConfig
                final ArrayList<Media> select=intent.getParcelableArrayListExtra(PickerConfig.EXTRA_RESULT);

> my_proj/platforms/android/app/src/main/java/com/dmc/mediaPickerPlugin/MediaPicker.java:166: error: cannot find symbol Media
                            for(Media media:select){

**Comment by ajmeese7** [comment]
I just installed and built the latest version this morning with Cordova (not Ionic) and it worked fine. Maybe try doing a pure Cordova build and see if that helps
